send:
  name: Send proactive notification
  description: Send a proactive notification (yellow ring) to Alexa devices
  fields:
    sender:
      name: Message
      description: "Text displayed in the notification after the skill name (e.g. 'notification from [skill name]: [this value]')"
      required: false
      example: "Front Door"
      default: "Home Assistant"
      selector:
        text:
    count:
      name: Message count
      description: Number of unread messages to display
      required: false
      example: 1
      default: 1
      selector:
        number:
          min: 1
          max: 99
          mode: box
