name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip integration
        run: |
          cd custom_components/alexa_proactive
          zip -r ../../alexa_proactive.zip .

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: alexa_proactive.zip
